version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8112:8111"
    volumes:
      - ./teamcity-server-data:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db

  teamcity-agent:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    volumes:
      - ./teamcity-agent-conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

  marketing:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./marketing-website/nginx.conf:/etc/nginx/nginx.conf
      - ./marketing-website/release-notes-response.json:/usr/share/nginx/html/release-notes-response.json
